language: java
os: linux
services:
- docker
env:
  global:
  - HXE_VERSION=2.00.036.00.20190223.1
  - 'PASSWORD_FILE_CONTENT=''{"master_password" : "L1qu1base_test"}'''
  - PASSWORD_FILE_NAME=passwords.json
  - secure: d7P5qt4zyg2rxqc37BuHTP9tUKR8sFObgyCU9FxYZw+lS45qY/XR2ST3AYUygOz6tOqRVrrXDyixfnZLpsgYE3ZMqu4A/64RIa34eK4iZoT2c9ow5bBONcpk92XUlVfJtgDE3PZ0z27IhnEc+qiW2epkc+8AQzSMsrVcTnWQ8FR8X/Z2JdO4UhOvY78T1SapemIJymq8l79tEVORd3H9dSNBpZh3WOgzmJT5LvmpjzMhjt5T82VM+ES7GuKDZJ2J4KMrr6uTQgYnWZ8bivKi2V7h7epCv0EoKUE562xpEiSHpio5xxqsAIy5dpKsXIpZTqpm9/HAPnHGTSgRmUeIsgIdgNxcvRTMh1z795kgX4tFKSxTex8Tk9BPvaudLz/s+xF5VY/jBW6VBx7Z10uLRcWbs/ILoy88dxfdPT/coHxULd42N7gftt4DyG7ROCQohlXh/9vFa6l3bSIlrNndBtjL3UOty2Iz5c2PCI0iu90QUqpJ4nuidhAqUB5xbIHMHZ76sP1qLqRTCSJXOeocB/xPe9+v/p+DSTGatGcXbmgpXq0dB8jV56J9qNqVOFQqtppVZMIXy4PzHOG8wRTdhNwAeHRmQSIurnWQ/qG/ZHZpcsSEvCjl3pMU0/Gjjz64Sx3qK5DvEzWCVgAfpcELmt+2oLuQg0PFXMqqlKPZpUk=
  - secure: Rc/S7d9FstZ6UYsS6XpRVs4cquBUezECi1Lmd1bEIU0zu//JeUsJvFDZeLGcCvMDE8c6wbDsmn41iZJkrk0GNkp+QbMpD+c8fF+h8h6ky3DniWJoFnt0XOoLqF/D4zuxJfEcAYPhvxxC02R6tyTum2kVlmC+AtWnfGP1Ae7/1sOPua8eAb1EftlGXbCdzxJfOXKbR1D2j5gFN3kiNcIKVRJDKUJawdyVWrwp583buRgowyGFgsP0eeFrSGdvGlGkHGwpGe5a8NAo8XzNrQOmGBE8DJlDk140fYNecmIWm5Rf26gpdzP1LBIqWAEUk1gUGQH9Y53HQY9AAYLjBHAwHJM2DEEeTso5t403PWaCKpHkdQlL+dkNy4z1JvmXYjCRt8bYhteA89bnCngfMw6A198wQavI9gun9J8l31PT9yYPowute1p5nCv1CeO1JuUC/TW0qGmz+9b8KMuR4LQcGu8rkhffwrIhFtkhZ8U/3mdteGIG0TDBVJxz5T2UMb4/VRHJ2Pv4ZR4WE6Y/dWvmCEWkO5oG1MsJz4Tnm+70A1reu2T092Y1uWM93yOzt79u6SNXlAwVnPdx6Q8huQMcnCP7AgYE7sSZhA12q597ji2k8urxM4UCG0dde4drYOfu4WJdbOTHGXJegMayJQnTEdyvPDi5Wag421YoT1qRoLs=
before_script:
- mkdir $TRAVIS_BUILD_DIR/HXE
- chmod -R 777 $TRAVIS_BUILD_DIR/HXE
- echo $PASSWORD_FILE_CONTENT > $TRAVIS_BUILD_DIR/HXE/$PASSWORD_FILE_NAME
- chmod 777 $TRAVIS_BUILD_DIR/HXE/$PASSWORD_FILE_NAME
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker pull store/saplabs/hanaexpress:$HXE_VERSION
- docker run -d -p 39013:39013 -p 39015:39015 -p 39017:39017 -p 39041-39045:39041-39045
  -p 1128-1129:1128-1129 -p 59013-59014:59013-59014 -v $TRAVIS_BUILD_DIR/HXE:/hana/mounts
  --ulimit nofile=1048576:1048576 --sysctl kernel.shmmax=1073741824 --sysctl net.ipv4.ip_local_port_range='40000
  60999' --sysctl kernel.shmmni=524288 --sysctl kernel.shmall=8388608 --name HXETravisCI
  store/saplabs/hanaexpress:$HXE_VERSION --passwords-url file:///hana/mounts/$PASSWORD_FILE_NAME
  --agree-to-sap-license
- sleep 10
- "while true; do \n  STARTING_CONTAINERS=`docker ps --filter \"name=HXETravisCI\"
  --format \"{{.Names}} {{.Status}}\" | grep 'health: starting' | wc -l`;\n  echo
  \"Waiting for $STARTING_CONTAINERS HANA container(s) to finish startup\";\n  if
  [ $STARTING_CONTAINERS -ne 1 ]; then\n    break; \n  fi;\n  sleep 5; \ndone"
- docker ps -a
- docker exec HXETravisCI bash -l -c "hdbsql -u SYSTEM -p L1qu1base_test -i 90 -d
  HXE 'CREATE USER LIQUIBASE_TEST PASSWORD L1qu1base_test NO FORCE_FIRST_PASSWORD_CHANGE'"
- docker logout
addons:
  hosts:
  - hxehost
